version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: samadhan
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nextjs-app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/samadhan
      DIRECT_URL: postgres://postgres:postgres@postgres:5432/samadhan
    ports:
      - "3000:3000"
    env_file:
      - .env

volumes:
  postgres-data:
